image:
  repository: wordpress
  tag: "6.4-apache"
  pullPolicy: IfNotPresent

storage:
  size: 2Gi
  storageClass: local-path

ingress:
  enabled: true

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"