image:
  repository: wordpress
  tag: "6.7-apache"
  pullPolicy: IfNotPresent

storage:
  size: 2Gi
  storageClass: local-path

ingress:
  enabled: true

replicas: 3

resources:
  requests:
    memory: "256Mi"
    cpu: "150m"
  limits:
    memory: "512Mi"
    cpu: "250m"