image:
  repository: wordpress
  tag: "php8.3-fpm-alpine"
  pullPolicy: IfNotPresent

storage:
  size: 2Gi
  storageClass: local-path

ingress:
  enabled: true

replicas: 3

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"