image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

storage:
  size: 10Gi
  storageClass: microk8s-hostpath

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

mysql:
  rootPassword: ""
  user: wordpress
  password: ""
  database: wordpress