image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

storage:
  size: 2Gi
  storageClass: local-path

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "750m"

replicas: 1

mysql:
  rootPassword: ""
  user: wordpress
  password: ""
  database: wordpress