apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: wordpress
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: wordpress
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: WORDPRESS_DB_USER
          valueFrom:
          secretKeyRef:
            name: {{ .Release.Name }}-mysql-secret
            key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
          secretKeyRef:
            name: {{ .Release.Name }}-mysql-secret
            key: mysql-database
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          failureThreshold: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wordpress-pvc