apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: wordpress
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: http-port
    name: http-sv-port
  selector:
    app: wordpress
    release: {{ .Release.Name }}